### ISSUE TITLE
Remove Closed Source Projects

### ISSUE THREAD

**Issue by tursics** [technologiestiftung/berlin-open-source-portal#147]
Public visible code is not Open Source. An Open Source Project needs an Open License. The project "Kunst im öffentlichen Raum Pankow" does not define a license. So this project is not open source.

Please discuss different solutions:
- remove this project from the list
- mark this project as a candidate for Open Source
- get in touch with the project host to define a valid license on github
- more ideas?

Thanks,
Thomas

**Comment by tursics** [comment]
Thanks Tori. That would be perfect.

Projects with MIT license must contain the complete license text somewhere. "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." The LICENSE file is the best solutions for that

**Comment by tori-d** [comment]
Ok, there is now a LICENSE file in the repo in question (https://github.com/cpietsch/vikus-viewer/blob/master/LICENSE.md) and our entry for the project is also updated (https://berlinopensource.de/projekt/kunst_pankow/). Accordingly, I'll now close this issue :)
